CREATE TABLE reframe_mistakes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES reframe_users(id) NOT NULL,
    posting_date DATE NOT NULL,
    mistake_nickname VARCHAR (100) NOT NULL,
    mistake VARCHAR (1000) NOT NULL,
    box_checked BOOLEAN NOT NULL,
    went_wrong VARCHAR (1000) NOT NULL,
    why_wrong VARCHAR (1000) NOT NULL,
    what_doing VARCHAR (1000) NOT NULL,
    what_learn VARCHAR (1000) NOT NULL,
    plan_one VARCHAR (500) NOT NULL,
    plan_two VARCHAR (500) NULL,
    plan_three VARCHAR (500) NULL,
    plan_four VARCHAR (500) NULL,
    plan_five VARCHAR (500) NULL
);