CREATE TABLE reframe_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mistake_id INTEGER REFERENCES reframe_mistakes(id) NOT NULL,
    comment VARCHAR (1000) NULL,
    liked BOOLEAN NULL,
    disliked BOOLEAN NULL
);